// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: frontier/v1/frontier.proto

package frontier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrontierClient is the client API for Frontier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontierClient interface {
	// Start crawling seed
	CrawlSeed(ctx context.Context, in *CrawlSeedRequest, opts ...grpc.CallOption) (*CrawlExecutionId, error)
	// Request a URI from the Frontiers queue.
	// Used by a Harvester to fetch a new page. If no URI is ready for harvesting, Frontier should return
	// gRPC status NOT_FOUND. Harvester should then retry the request after a reasonable backoff time.
	GetNextPage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PageHarvestSpec, error)
	// Inform Frontier that a page fetch was finished.
	// Contains metrics, outlinks and error as a stream of messages. Client closes stream when finished.
	PageCompleted(ctx context.Context, opts ...grpc.CallOption) (Frontier_PageCompletedClient, error)
	// The number of busy CrawlHostGroups which essentially is the number of web pages currently downloading
	BusyCrawlHostGroupCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountResponse, error)
	// Total number of queued URI's
	QueueCountTotal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountResponse, error)
	// Number of queued URI's for a CrawlExecution
	QueueCountForCrawlExecution(ctx context.Context, in *CrawlExecutionId, opts ...grpc.CallOption) (*CountResponse, error)
	// Number of queued URI's for a CrawlHostGroup
	QueueCountForCrawlHostGroup(ctx context.Context, in *CrawlHostGroup, opts ...grpc.CallOption) (*CountResponse, error)
}

type frontierClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontierClient(cc grpc.ClientConnInterface) FrontierClient {
	return &frontierClient{cc}
}

func (c *frontierClient) CrawlSeed(ctx context.Context, in *CrawlSeedRequest, opts ...grpc.CallOption) (*CrawlExecutionId, error) {
	out := new(CrawlExecutionId)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/CrawlSeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierClient) GetNextPage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PageHarvestSpec, error) {
	out := new(PageHarvestSpec)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/GetNextPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierClient) PageCompleted(ctx context.Context, opts ...grpc.CallOption) (Frontier_PageCompletedClient, error) {
	stream, err := c.cc.NewStream(ctx, &Frontier_ServiceDesc.Streams[0], "/veidemann.api.frontier.v1.Frontier/PageCompleted", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontierPageCompletedClient{stream}
	return x, nil
}

type Frontier_PageCompletedClient interface {
	Send(*PageHarvest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type frontierPageCompletedClient struct {
	grpc.ClientStream
}

func (x *frontierPageCompletedClient) Send(m *PageHarvest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *frontierPageCompletedClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontierClient) BusyCrawlHostGroupCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/BusyCrawlHostGroupCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierClient) QueueCountTotal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/QueueCountTotal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierClient) QueueCountForCrawlExecution(ctx context.Context, in *CrawlExecutionId, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/QueueCountForCrawlExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierClient) QueueCountForCrawlHostGroup(ctx context.Context, in *CrawlHostGroup, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/veidemann.api.frontier.v1.Frontier/QueueCountForCrawlHostGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontierServer is the server API for Frontier service.
// All implementations must embed UnimplementedFrontierServer
// for forward compatibility
type FrontierServer interface {
	// Start crawling seed
	CrawlSeed(context.Context, *CrawlSeedRequest) (*CrawlExecutionId, error)
	// Request a URI from the Frontiers queue.
	// Used by a Harvester to fetch a new page. If no URI is ready for harvesting, Frontier should return
	// gRPC status NOT_FOUND. Harvester should then retry the request after a reasonable backoff time.
	GetNextPage(context.Context, *emptypb.Empty) (*PageHarvestSpec, error)
	// Inform Frontier that a page fetch was finished.
	// Contains metrics, outlinks and error as a stream of messages. Client closes stream when finished.
	PageCompleted(Frontier_PageCompletedServer) error
	// The number of busy CrawlHostGroups which essentially is the number of web pages currently downloading
	BusyCrawlHostGroupCount(context.Context, *emptypb.Empty) (*CountResponse, error)
	// Total number of queued URI's
	QueueCountTotal(context.Context, *emptypb.Empty) (*CountResponse, error)
	// Number of queued URI's for a CrawlExecution
	QueueCountForCrawlExecution(context.Context, *CrawlExecutionId) (*CountResponse, error)
	// Number of queued URI's for a CrawlHostGroup
	QueueCountForCrawlHostGroup(context.Context, *CrawlHostGroup) (*CountResponse, error)
	mustEmbedUnimplementedFrontierServer()
}

// UnimplementedFrontierServer must be embedded to have forward compatible implementations.
type UnimplementedFrontierServer struct {
}

func (UnimplementedFrontierServer) CrawlSeed(context.Context, *CrawlSeedRequest) (*CrawlExecutionId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlSeed not implemented")
}
func (UnimplementedFrontierServer) GetNextPage(context.Context, *emptypb.Empty) (*PageHarvestSpec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextPage not implemented")
}
func (UnimplementedFrontierServer) PageCompleted(Frontier_PageCompletedServer) error {
	return status.Errorf(codes.Unimplemented, "method PageCompleted not implemented")
}
func (UnimplementedFrontierServer) BusyCrawlHostGroupCount(context.Context, *emptypb.Empty) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusyCrawlHostGroupCount not implemented")
}
func (UnimplementedFrontierServer) QueueCountTotal(context.Context, *emptypb.Empty) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCountTotal not implemented")
}
func (UnimplementedFrontierServer) QueueCountForCrawlExecution(context.Context, *CrawlExecutionId) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCountForCrawlExecution not implemented")
}
func (UnimplementedFrontierServer) QueueCountForCrawlHostGroup(context.Context, *CrawlHostGroup) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCountForCrawlHostGroup not implemented")
}
func (UnimplementedFrontierServer) mustEmbedUnimplementedFrontierServer() {}

// UnsafeFrontierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontierServer will
// result in compilation errors.
type UnsafeFrontierServer interface {
	mustEmbedUnimplementedFrontierServer()
}

func RegisterFrontierServer(s grpc.ServiceRegistrar, srv FrontierServer) {
	s.RegisterService(&Frontier_ServiceDesc, srv)
}

func _Frontier_CrawlSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).CrawlSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/CrawlSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).CrawlSeed(ctx, req.(*CrawlSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frontier_GetNextPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).GetNextPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/GetNextPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).GetNextPage(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frontier_PageCompleted_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FrontierServer).PageCompleted(&frontierPageCompletedServer{stream})
}

type Frontier_PageCompletedServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*PageHarvest, error)
	grpc.ServerStream
}

type frontierPageCompletedServer struct {
	grpc.ServerStream
}

func (x *frontierPageCompletedServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *frontierPageCompletedServer) Recv() (*PageHarvest, error) {
	m := new(PageHarvest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Frontier_BusyCrawlHostGroupCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).BusyCrawlHostGroupCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/BusyCrawlHostGroupCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).BusyCrawlHostGroupCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frontier_QueueCountTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).QueueCountTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/QueueCountTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).QueueCountTotal(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frontier_QueueCountForCrawlExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlExecutionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).QueueCountForCrawlExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/QueueCountForCrawlExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).QueueCountForCrawlExecution(ctx, req.(*CrawlExecutionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frontier_QueueCountForCrawlHostGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlHostGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).QueueCountForCrawlHostGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.frontier.v1.Frontier/QueueCountForCrawlHostGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).QueueCountForCrawlHostGroup(ctx, req.(*CrawlHostGroup))
	}
	return interceptor(ctx, in, info, handler)
}

// Frontier_ServiceDesc is the grpc.ServiceDesc for Frontier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Frontier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.frontier.v1.Frontier",
	HandlerType: (*FrontierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlSeed",
			Handler:    _Frontier_CrawlSeed_Handler,
		},
		{
			MethodName: "GetNextPage",
			Handler:    _Frontier_GetNextPage_Handler,
		},
		{
			MethodName: "BusyCrawlHostGroupCount",
			Handler:    _Frontier_BusyCrawlHostGroupCount_Handler,
		},
		{
			MethodName: "QueueCountTotal",
			Handler:    _Frontier_QueueCountTotal_Handler,
		},
		{
			MethodName: "QueueCountForCrawlExecution",
			Handler:    _Frontier_QueueCountForCrawlExecution_Handler,
		},
		{
			MethodName: "QueueCountForCrawlHostGroup",
			Handler:    _Frontier_QueueCountForCrawlHostGroup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PageCompleted",
			Handler:       _Frontier_PageCompleted_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "frontier/v1/frontier.proto",
}
