// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package urlcanonicalizer

import (
	context "context"
	v1 "github.com/nlnwa/veidemann-api/go/frontier/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// UrlCanonicalizerServiceClient is the client API for UrlCanonicalizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlCanonicalizerServiceClient interface {
	// Canonicalize URL
	CanonicalizeUrl(ctx context.Context, in *v1.QueuedUri, opts ...grpc.CallOption) (*v1.QueuedUri, error)
}

type urlCanonicalizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlCanonicalizerServiceClient(cc grpc.ClientConnInterface) UrlCanonicalizerServiceClient {
	return &urlCanonicalizerServiceClient{cc}
}

func (c *urlCanonicalizerServiceClient) CanonicalizeUrl(ctx context.Context, in *v1.QueuedUri, opts ...grpc.CallOption) (*v1.QueuedUri, error) {
	out := new(v1.QueuedUri)
	err := c.cc.Invoke(ctx, "/veidemann.api.urlcanonicalizer.v1.UrlCanonicalizerService/CanonicalizeUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlCanonicalizerServiceServer is the server API for UrlCanonicalizerService service.
// All implementations must embed UnimplementedUrlCanonicalizerServiceServer
// for forward compatibility
type UrlCanonicalizerServiceServer interface {
	// Canonicalize URL
	CanonicalizeUrl(context.Context, *v1.QueuedUri) (*v1.QueuedUri, error)
	mustEmbedUnimplementedUrlCanonicalizerServiceServer()
}

// UnimplementedUrlCanonicalizerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUrlCanonicalizerServiceServer struct {
}

func (UnimplementedUrlCanonicalizerServiceServer) CanonicalizeUrl(context.Context, *v1.QueuedUri) (*v1.QueuedUri, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanonicalizeUrl not implemented")
}
func (UnimplementedUrlCanonicalizerServiceServer) mustEmbedUnimplementedUrlCanonicalizerServiceServer() {
}

// UnsafeUrlCanonicalizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlCanonicalizerServiceServer will
// result in compilation errors.
type UnsafeUrlCanonicalizerServiceServer interface {
	mustEmbedUnimplementedUrlCanonicalizerServiceServer()
}

func RegisterUrlCanonicalizerServiceServer(s grpc.ServiceRegistrar, srv UrlCanonicalizerServiceServer) {
	s.RegisterService(&_UrlCanonicalizerService_serviceDesc, srv)
}

func _UrlCanonicalizerService_CanonicalizeUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.QueuedUri)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlCanonicalizerServiceServer).CanonicalizeUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.urlcanonicalizer.v1.UrlCanonicalizerService/CanonicalizeUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlCanonicalizerServiceServer).CanonicalizeUrl(ctx, req.(*v1.QueuedUri))
	}
	return interceptor(ctx, in, info, handler)
}

var _UrlCanonicalizerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.urlcanonicalizer.v1.UrlCanonicalizerService",
	HandlerType: (*UrlCanonicalizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanonicalizeUrl",
			Handler:    _UrlCanonicalizerService_CanonicalizeUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urlcanonicalizer/v1/urlcanonicalizer.proto",
}
