name: Generate Go stubs

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'go/v') == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.API_COMMIT_PAT }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Generate sources
        run: |
          PATH=/home/runner/go/bin:${PATH}
          make clean all

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit changes and create tag
        with:
          commit_message: Generate Golang source
          branch: master
          push_options: '--force'
          tagging_message: ${{ format('go/{0}', github.event.release.tag_name) }}
